# Regenerates the builtin lists of `languages/janet/highlights.scm` from the running Janet: the
# functions, the other values and the macros of `root-env`. Rerun after a Janet upgrade:
#
#   janet scripts/highlights.janet languages/janet/highlights.scm
#
# It rewrites the lines between the `; BEGIN generated` and `; END generated` markers in place.

(def- usage "usage: janet scripts/highlights.janet <highlights.scm>")

(def- begin-marker "; BEGIN generated by scripts/highlights.janet")
(def- end-marker "; END generated by scripts/highlights.janet")

# Regex metacharacters, escaped once for the regex and once more for the query string literal.
(defn- highlights/escape [name]
  (def out @"")
  (each byte name
    (when (index-of byte (string/bytes `\.*+?()[]{}|^$`))
      (buffer/push-string out `\\`))
    (buffer/push-byte out byte))
  (string out))

(defn- highlights/regex [names]
  (string `"^(` (string/join (map highlights/escape (sort names)) "|") `)$"`))

(defn- highlights/kind [name]
  (def binding (in root-env (symbol name)))
  (def value (in binding :value))
  (cond
    (in binding :macro) :macro
    (or (function? value) (cfunction? value)) :function
    # `*out*` and friends are `@variable.special` already.
    (string/has-prefix? "*" name) nil
    :constant))

(defn- highlights/section []
  (def kinds (group-by highlights/kind (map string (all-bindings root-env))))
  (string/join
    [begin-marker
     "; builtin functions"
     "((sym_lit) @function.builtin"
     (string "  (#match? @function.builtin\n    " (highlights/regex (kinds :function)) "))")
     ""
     "; builtin values"
     "((sym_lit) @constant.builtin"
     (string "  (#match? @constant.builtin\n    " (highlights/regex (kinds :constant)) "))")
     ""
     "; macros"
     "(par_tup_lit"
     "  ."
     "  (sym_lit) @keyword"
     (string "  (#match? @keyword\n    " (highlights/regex (kinds :macro)) "))")
     end-marker]
    "\n"))

(defn main [_ &opt file]
  (unless file (error usage))
  (def source (slurp file))
  (def begin (string/find begin-marker source))
  (def end (string/find end-marker source))
  (unless (and begin end) (errorf "%s: no generated section" file))
  (spit file
        (string (string/slice source 0 begin)
                (highlights/section)
                (string/slice source (+ end (length end-marker))))))
